# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x05\x65vent\"_\n\tUIElement\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\t\n\x01x\x18\x04 \x01(\x05\x12\t\n\x01y\x18\x05 \x01(\x05\x12\t\n\x01w\x18\x06 \x01(\x05\x12\t\n\x01h\x18\x07 \x01(\x05\"J\n\x0bScreenEvent\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\x0b\n\x03png\x18\x02 \x01(\x0c\x12\"\n\x08\x65lements\x18\x03 \x03(\x0b\x32\x10.event.UIElement\"M\n\x06Intent\x12\n\n\x02ts\x18\x01 \x01(\x03\x12#\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x13.event.IntentAction\x12\x12\n\nelement_id\x18\x03 \x01(\x03*\x1e\n\x0cIntentAction\x12\x0e\n\nLOOK_CLICK\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTENTACTION']._serialized_start=274
  _globals['_INTENTACTION']._serialized_end=304
  _globals['_UIELEMENT']._serialized_start=22
  _globals['_UIELEMENT']._serialized_end=117
  _globals['_SCREENEVENT']._serialized_start=119
  _globals['_SCREENEVENT']._serialized_end=193
  _globals['_INTENT']._serialized_start=195
  _globals['_INTENT']._serialized_end=272
# @@protoc_insertion_point(module_scope)
